sudo: required
services:
  - docker

before_install:
  - docker build -t cyberlkhome/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cyberlkhome/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-126756998778"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"