version: '3.3'

services:
  web:
    image: my-react-app
    container_name: my_react_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /app/node_modules
      - .:/app